# Generated by Django 4.2.16 on 2024-11-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
