# Generated by Django 4.2.16 on 2024-11-26 08:25

from django.db import migrations, models
import objectdetection.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDetectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=objectdetection.models.objectdetection_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
