# Generated by Django 4.2.16 on 2024-11-26 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objectdetection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectdetectionimage',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='objectdetection_images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
