# Generated by Django 4.2.16 on 2024-11-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
