# Generated by Django 4.2.16 on 2024-11-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
