# Generated by Django 4.2.16 on 2024-11-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
