# Generated by Django 4.2.16 on 2024-11-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(choices=[('info', 'Info'), ('alert', 'Alert'), ('deposit', 'Deposit'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=50),
        ),
    ]
